on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cxx: g++
          - os: ubuntu-latest
            cxx: clang++
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v4
      - run: cmake --preset debug
      - run: cmake --build build/debug --config Debug
      - run: ctest --test-dir build/debug -C Debug --output-on-failure
